-- Seed OPCIONAL para D1 (producción).
--
-- En producción el email está deshabilitado, así que el flujo recomendado es:
--   1. Registrar la cuenta normalmente desde la UI (queda email_verificado = 0).
--   2. El administrador la verifica a mano:
--        wrangler d1 execute micelio-prod --remote \
--          --command "UPDATE usuarios SET email_verificado = 1 WHERE email = 'usuario@ejemplo.com'"
--
-- Si en cambio prefieres pre-sembrar un usuario admin sin pasar por la UI,
-- completa los placeholders de abajo y ejecútalo una vez:
--   wrangler d1 execute micelio-prod --remote --file=backend/migrations/d1/seed.sql
--
-- El password_hash debe ser un hash BCrypt. Para generarlo puedes registrar el
-- usuario por la UI y copiar el hash con:
--   wrangler d1 execute micelio-prod --remote \
--     --command "SELECT password_hash FROM usuarios WHERE email='...'"
-- (o generarlo con cualquier utilidad BCrypt). Los ids son UUID cualquiera.

-- INSERT INTO usuarios (id, email, nombre, password_hash, email_verificado, creado_en, actualizado_en)
-- VALUES (
--   'REEMPLAZAR-uuid-usuario',
--   'admin@ejemplo.com',
--   'Admin',
--   'REEMPLAZAR-bcrypt-hash',
--   1,
--   '2026-01-01T00:00:00.0000000Z',
--   '2026-01-01T00:00:00.0000000Z'
-- );
--
-- INSERT INTO vaults (id, nombre, propietario_id, creado_en)
-- VALUES ('REEMPLAZAR-uuid-vault', 'Mi vault', 'REEMPLAZAR-uuid-usuario', '2026-01-01T00:00:00.0000000Z');
--
-- INSERT INTO membresias (id, usuario_id, recurso_tipo, recurso_id, rol, creado_en)
-- VALUES ('REEMPLAZAR-uuid-membresia', 'REEMPLAZAR-uuid-usuario', 'vault', 'REEMPLAZAR-uuid-vault', 'propietario', '2026-01-01T00:00:00.0000000Z');
