// GENERADO por scripts/generar-ayuda.mjs — NO EDITAR A MANO.
// Fuente: ayuda/<NN-tema>/<NN-subtema>.md. Para regenerar:
//
//   node scripts/generar-ayuda.mjs   (o npm run generar-ayuda)

/** Una página de la ayuda (`FUN-L-27`). */
export type PaginaAyuda = {
  /** `<tema>/<subtema>`, sin los números de orden: lo que usan los enlaces `ayuda:`. */
  id: string;
  titulo: string;
  tema: string;
  /** Solo existe en esa versión; `null` = en las dos. */
  solo: "desktop" | "web" | null;
  /** Está en el índice pero todavía no se escribió («próximamente»). */
  pendiente: boolean;
  /** Herramientas que documenta (tipos de `lib/extensionesDeTipo`), para el test de cobertura. */
  cubre: readonly string[];
  /** Otras palabras con las que se la busca. */
  sinonimos: readonly string[];
  /** Markdown, sin el frontmatter. */
  cuerpo: string;
  /** Texto plano del cuerpo, para el buscador. */
  texto: string;
};

/** Un tema del índice, con sus páginas en orden. */
export type TemaAyuda = { slug: string; titulo: string; paginas: readonly PaginaAyuda[] };

export const TEMAS_AYUDA: readonly TemaAyuda[] = [
  {
    slug: "primeros-pasos",
    titulo: "Primeros pasos",
    paginas: [
      {
        id: "primeros-pasos/que-es-un-vault",
        titulo: "Qué es un vault",
        tema: "Primeros pasos",
        solo: null,
        pendiente: false,
        cubre: [],
        sinonimos: ["bóveda","carpeta","empezar","inicio","introducción"],
        cuerpo: "Un **vault** es una carpeta de tu computadora que Mycelium abre como tu red de notas. No\nhay una base de datos escondida ni un formato propio: cada nota es un archivo `.md`, texto\nplano en Markdown, que podés abrir con cualquier otro programa, copiar o respaldar como\ncualquier archivo.\n\n## Para qué sirve\n\nTodo lo que escribís vive ahí: notas, dibujos, lienzos, diagramas e imágenes. Mycelium lee\nla carpeta, arma un índice para buscar al instante y dibuja las conexiones entre tus notas.\nSi algún día dejás de usar Mycelium, tus notas siguen siendo tuyas y legibles.\n\n## Cómo se usa\n\n1. Al abrir Mycelium, elegí una carpeta: una vacía para empezar de cero o una que ya tenga\n   notas, como una que usabas con Obsidian.\n2. Creá una nota con **Ctrl+P** → «Nueva nota», o desde el explorador. El\n   nombre del archivo es su título: [cambiar uno cambia el otro](ayuda:escribir-notas/el-titulo-renombra).\n3. Enlazá notas escribiendo `[[` y el título de otra. Esos enlaces son la red.\n\n```ejemplo\nHoy hablé con Ana sobre el [[Proyecto Faro]]. #reunión\n```\n\n## Qué hay en la carpeta\n\n| En la carpeta | Qué es |\n|---|---|\n| `Algo.md` | Una nota. Su nombre es su título. |\n| `.base`, `.canvas`, `.excalidraw`, `.drawio` | Tablas, lienzos, dibujos y diagramas. |\n| PDF, imágenes y otros | Se abren en el visor, pero no entran en la búsqueda. |\n| `.mycelium/` | Lo que Mycelium guarda para sí: el índice, la papelera, el calendario y las preferencias del vault. |\n\n> [!warning] No toques `.mycelium/`\n> Es interno. Borrarlo no pierde tus notas, pero sí la papelera y los recordatorios.\n\n> [!tip] Un vault por tema de tu vida\n> Podés tener varios (trabajo, estudio, personal) y abrir cada uno en su propia ventana.\n",
        texto: "Un vault es una carpeta de tu computadora que Mycelium abre como tu red de notas. No hay una base de datos escondida ni un formato propio: cada nota es un archivo .md, texto plano en Markdown, que podés abrir con cualquier otro programa, copiar o respaldar como cualquier archivo. Para qué sirve Todo lo que escribís vive ahí: notas, dibujos, lienzos, diagramas e imágenes. Mycelium lee la carpeta, arma un índice para buscar al instante y dibuja las conexiones entre tus notas. Si algún día dejás de usar Mycelium, tus notas siguen siendo tuyas y legibles. Cómo se usa Al abrir Mycelium, elegí una carpeta: una vacía para empezar de cero o una que ya tenga notas, como una que usabas con Obsidian. Creá una nota con Ctrl+P → «Nueva nota», o desde el explorador. El nombre del archivo es su título: cambiar uno cambia el otro. Enlazá notas escribiendo y el título de otra. Esos enlaces son la red. Hoy hablé con Ana sobre el [[Proyecto Faro. #reunión Qué hay en la carpeta En la carpeta Qué es ------ Algo.md Una nota. Su nombre es su título. .base, .canvas, .excalidraw, .drawio Tablas, lienzos, dibujos y diagramas. PDF, imágenes y otros Se abren en el visor, pero no entran en la búsqueda. .mycelium/ Lo que Mycelium guarda para sí: el índice, la papelera, el calendario y las preferencias del vault. No toques .mycelium/ Es interno. Borrarlo no pierde tus notas, pero sí la papelera y los recordatorios. Un vault por tema de tu vida Podés tener varios (trabajo, estudio, personal) y abrir cada uno en su propia ventana.",
      },
      {
        id: "primeros-pasos/abrir-y-cambiar-de-vault",
        titulo: "Abrir y cambiar de vault",
        tema: "Primeros pasos",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: [],
        cuerpo: "",
        texto: "",
      },
      {
        id: "primeros-pasos/la-interfaz",
        titulo: "La interfaz",
        tema: "Primeros pasos",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: [],
        cuerpo: "",
        texto: "",
      },
    ],
  },
  {
    slug: "escribir-notas",
    titulo: "Escribir notas",
    paginas: [
      {
        id: "escribir-notas/vista-en-vivo-y-lectura",
        titulo: "Vista en vivo y lectura",
        tema: "Escribir notas",
        solo: null,
        pendiente: true,
        cubre: ["markdown"],
        sinonimos: ["modo lectura","dividido","editor"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "escribir-notas/el-titulo-renombra",
        titulo: "El título renombra el archivo",
        tema: "Escribir notas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["renombrar","nombre del archivo"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "escribir-notas/enfasis",
        titulo: "Énfasis",
        tema: "Escribir notas",
        solo: null,
        pendiente: false,
        cubre: [],
        sinonimos: ["negrita","cursiva","guion bajo","asterisco","resaltar","degradado","tachado"],
        cuerpo: "El **énfasis** destaca una palabra o una frase: cursiva, negrita o las dos. En Markdown se\nmarca con asteriscos (`*`) o con guiones bajos (`_`) alrededor del texto. Para casi\ncualquier programa son lo mismo; **Mycelium los distingue**: el guion bajo, además, le da\ncolor.\n\n## Para qué sirve\n\nCon asteriscos tenés el énfasis de siempre. Con guiones bajos tenés una segunda capa para\nlo que querés que salte a la vista —un término clave, una advertencia— sin recurrir a\notra sintaxis. Si abrís la nota en otro programa, se sigue viendo como cursiva o negrita:\nno se pierde nada.\n\n## Cómo se usa\n\n1. Rodeá el texto con uno, dos o tres símbolos iguales, sin espacios entre el símbolo y el\n   texto.\n2. Elegí `*` para el estilo clásico o `_` para la versión con color.\n\n| Escribís | Se ve |\n|---|---|\n| `*texto*` | cursiva |\n| `_texto_` | cursiva, con el color de brillo del tema |\n| `**texto**` | negrita |\n| `__texto__` | negrita, con el color de acento del tema |\n| `***texto***` | negrita y cursiva |\n| `___texto___` | negrita **sin** cursiva, con un degradado del brillo al acento |\n| `~~texto~~` | tachado |\n\n```ejemplo\n*cursiva* y _cursiva con brillo_\n\n**negrita** y __negrita con acento__\n\n***negrita y cursiva*** y ___negrita con degradado___\n\n~~tachado~~\n```\n\n> [!info] En medio de una palabra, el guion bajo no estiliza\n> `nombre_de_archivo` queda tal cual, como en cualquier Markdown. Si querés destacar una\n> parte de una palabra, usá asteriscos: `super*cali*fragilístico`.\n\n```ejemplo\nnombre_de_archivo y super*cali*fragilístico\n```\n\nEn la vista en vivo los símbolos se esconden cuando el cursor no está en la línea, y\nreaparecen al volver a ella para que los puedas editar.\n",
        texto: "El énfasis destaca una palabra o una frase: cursiva, negrita o las dos. En Markdown se marca con asteriscos () o con guiones bajos () alrededor del texto. Para casi cualquier programa son lo mismo; Mycelium los distingue: el guion bajo, además, le da color. Para qué sirve Con asteriscos tenés el énfasis de siempre. Con guiones bajos tenés una segunda capa para lo que querés que salte a la vista —un término clave, una advertencia— sin recurrir a otra sintaxis. Si abrís la nota en otro programa, se sigue viendo como cursiva o negrita: no se pierde nada. Cómo se usa Rodeá el texto con uno, dos o tres símbolos iguales, sin espacios entre el símbolo y el texto. Elegí para el estilo clásico o para la versión con color. Escribís Se ve ------ texto cursiva texto cursiva, con el color de brillo del tema texto negrita texto negrita, con el color de acento del tema texto negrita y cursiva texto negrita sin cursiva, con un degradado del brillo al acento texto tachado cursiva y cursiva con brillo negrita y negrita con acento negrita y cursiva y negrita con degradado tachado En medio de una palabra, el guion bajo no estiliza nombredearchivo queda tal cual, como en cualquier Markdown. Si querés destacar una parte de una palabra, usá asteriscos: supercalifragilístico. nombredearchivo y supercalifragilístico En la vista en vivo los símbolos se esconden cuando el cursor no está en la línea, y reaparecen al volver a ella para que los puedas editar.",
      },
      {
        id: "escribir-notas/tareas",
        titulo: "Tareas y sus estados",
        tema: "Escribir notas",
        solo: null,
        pendiente: false,
        cubre: [],
        sinonimos: ["checkbox","casilla","pendiente","hecha","cancelada","lista de tareas","to-do"],
        cuerpo: "Una **tarea** es un ítem de lista con una casilla: `- [ ]`. El carácter entre los\ncorchetes es su **estado**. Además de pendiente y hecha, Mycelium entiende siete estados\nmás, con los mismos símbolos que los temas de Obsidian: el vault sigue siendo\nintercambiable.\n\n## Para qué sirve\n\nPara llevar el seguimiento dentro de la nota misma, sin otra herramienta: lo que está en\ncurso, lo que se pospuso, lo que se canceló o lo que tiene una pregunta abierta.\n\n## Cómo se usa\n\n1. Empezá una línea con `- [ ] ` (guion, espacio, corchetes con un espacio adentro y otro\n   espacio) y escribí la tarea.\n2. **Clic** en la casilla: una pendiente pasa a hecha; cualquier otra vuelve a pendiente.\n3. **Clic derecho** en la casilla: un menú con los nueve estados para elegir uno.\n\n```ejemplo\n- [ ] Pendiente\n- [x] Hecha\n- [/] En curso\n- [-] Cancelada\n- [>] Pospuesta\n- [*] Destacada\n- [!] Importante\n- [?] Pregunta\n- [+] Agregada\n```\n\nSolo **hecha** y **cancelada** cambian el texto: hecha lo apaga, cancelada lo tacha. Los\ndemás estados cambian solo la casilla. El estilo alcanza al texto propio del ítem; las\nsubtareas conservan el suyo:\n\n```ejemplo\n- [x] Preparar la reunión\n  - [ ] Mandar el resumen\n```\n\n> [!tip] Con el teclado\n> En la vista de lectura, Tab llega a la casilla, Espacio la alterna y la tecla de menú\n> (o Shift+F10) abre el menú de estados. En la vista en vivo, con el cursor en la línea\n> se ve el marcador en crudo y el símbolo se cambia a mano.\n\nCualquier otro símbolo entre los corchetes se ve como hecha. `- []` (sin espacio) o\n`- [xx]` no son tareas.\n",
        texto: "Una tarea es un ítem de lista con una casilla: - [ ]. El carácter entre los corchetes es su estado. Además de pendiente y hecha, Mycelium entiende siete estados más, con los mismos símbolos que los temas de Obsidian: el vault sigue siendo intercambiable. Para qué sirve Para llevar el seguimiento dentro de la nota misma, sin otra herramienta: lo que está en curso, lo que se pospuso, lo que se canceló o lo que tiene una pregunta abierta. Cómo se usa Empezá una línea con - [ ] (guion, espacio, corchetes con un espacio adentro y otro espacio) y escribí la tarea. Clic en la casilla: una pendiente pasa a hecha; cualquier otra vuelve a pendiente. Clic derecho en la casilla: un menú con los nueve estados para elegir uno. [ ] Pendiente [x] Hecha [/] En curso [-] Cancelada [>] Pospuesta [] Destacada [!] Importante [?] Pregunta [+] Agregada Solo hecha y cancelada cambian el texto: hecha lo apaga, cancelada lo tacha. Los demás estados cambian solo la casilla. El estilo alcanza al texto propio del ítem; las subtareas conservan el suyo: [x] Preparar la reunión [ ] Mandar el resumen Con el teclado En la vista de lectura, Tab llega a la casilla, Espacio la alterna y la tecla de menú (o Shift+F10) abre el menú de estados. En la vista en vivo, con el cursor en la línea se ve el marcador en crudo y el símbolo se cambia a mano. Cualquier otro símbolo entre los corchetes se ve como hecha. - [] (sin espacio) o - [xx] no son tareas.",
      },
      {
        id: "escribir-notas/callouts",
        titulo: "Callouts",
        tema: "Escribir notas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["avisos","admonitions","cajas"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "escribir-notas/tablas",
        titulo: "Tablas",
        tema: "Escribir notas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: [],
        cuerpo: "",
        texto: "",
      },
      {
        id: "escribir-notas/imagenes-y-embebidos",
        titulo: "Imágenes y archivos embebidos",
        tema: "Escribir notas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["embed","insertar","video","youtube"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "escribir-notas/formulas-y-diagramas",
        titulo: "Fórmulas y diagramas Mermaid",
        tema: "Escribir notas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["katex","latex","matemática","mermaid"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "escribir-notas/propiedades",
        titulo: "Propiedades",
        tema: "Escribir notas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["frontmatter","metadatos","yaml"],
        cuerpo: "",
        texto: "",
      },
    ],
  },
  {
    slug: "enlazar-y-organizar",
    titulo: "Enlazar y organizar",
    paginas: [
      {
        id: "enlazar-y-organizar/enlaces",
        titulo: "Enlaces, alias y embeds",
        tema: "Enlazar y organizar",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["wikilink","vínculo"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "enlazar-y-organizar/etiquetas",
        titulo: "Etiquetas",
        tema: "Enlazar y organizar",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["tags"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "enlazar-y-organizar/grafo",
        titulo: "Grafo",
        tema: "Enlazar y organizar",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["conexiones","red"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "enlazar-y-organizar/busqueda",
        titulo: "Búsqueda",
        tema: "Enlazar y organizar",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["buscar","paleta"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "enlazar-y-organizar/esporas",
        titulo: "Esporas",
        tema: "Enlazar y organizar",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["plantillas","templates"],
        cuerpo: "",
        texto: "",
      },
    ],
  },
  {
    slug: "tipos-de-archivo",
    titulo: "Tipos de archivo",
    paginas: [
      {
        id: "tipos-de-archivo/bases",
        titulo: "Bases",
        tema: "Tipos de archivo",
        solo: null,
        pendiente: true,
        cubre: ["base"],
        sinonimos: ["tabla","consulta"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "tipos-de-archivo/lienzos",
        titulo: "Lienzos",
        tema: "Tipos de archivo",
        solo: null,
        pendiente: true,
        cubre: ["canvas"],
        sinonimos: ["canvas","tablero"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "tipos-de-archivo/excalidraw",
        titulo: "Dibujos de Excalidraw",
        tema: "Tipos de archivo",
        solo: null,
        pendiente: true,
        cubre: ["excalidraw"],
        sinonimos: ["dibujo","boceto","pizarra"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "tipos-de-archivo/drawio",
        titulo: "Diagramas de draw.io",
        tema: "Tipos de archivo",
        solo: "desktop",
        pendiente: true,
        cubre: ["drawio"],
        sinonimos: ["diagrama","uml","flujo"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "tipos-de-archivo/otros-archivos",
        titulo: "Otros archivos",
        tema: "Tipos de archivo",
        solo: "desktop",
        pendiente: true,
        cubre: [],
        sinonimos: ["pdf","imagen","visor","soltar"],
        cuerpo: "",
        texto: "",
      },
    ],
  },
  {
    slug: "herramientas",
    titulo: "Herramientas",
    paginas: [
      {
        id: "herramientas/calendario",
        titulo: "Calendario",
        tema: "Herramientas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["recordatorios","agenda"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "herramientas/terminal",
        titulo: "Terminal",
        tema: "Herramientas",
        solo: "desktop",
        pendiente: true,
        cubre: [],
        sinonimos: ["consola","shell"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "herramientas/corrector",
        titulo: "Corrector ortográfico",
        tema: "Herramientas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["ortografía","diccionario"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "herramientas/papelera",
        titulo: "Papelera",
        tema: "Herramientas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: [],
        cuerpo: "",
        texto: "",
      },
      {
        id: "herramientas/exportar-e-importar",
        titulo: "Exportar e importar",
        tema: "Herramientas",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["pdf","respaldo","obsidian"],
        cuerpo: "",
        texto: "",
      },
    ],
  },
  {
    slug: "configuracion",
    titulo: "Configuración",
    paginas: [
      {
        id: "configuracion/mycignore",
        titulo: "Archivos ignorados (.mycignore)",
        tema: "Configuración",
        solo: "desktop",
        pendiente: true,
        cubre: [],
        sinonimos: ["ignorar","excluir","indexar"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "configuracion/css-y-snippets",
        titulo: "CSS y snippets",
        tema: "Configuración",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["estilos","tema","personalizar"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "configuracion/actualizaciones",
        titulo: "Actualizaciones",
        tema: "Configuración",
        solo: "desktop",
        pendiente: true,
        cubre: [],
        sinonimos: ["versión","actualizar"],
        cuerpo: "",
        texto: "",
      },
    ],
  },
  {
    slug: "ia",
    titulo: "IA",
    paginas: [
      {
        id: "ia/instrucciones-de-ia",
        titulo: "Instrucciones de IA del vault",
        tema: "IA",
        solo: "desktop",
        pendiente: true,
        cubre: [],
        sinonimos: ["claude","agente","memoria"],
        cuerpo: "",
        texto: "",
      },
      {
        id: "ia/control-de-la-ia",
        titulo: "Control de la IA (MCP)",
        tema: "IA",
        solo: "desktop",
        pendiente: true,
        cubre: [],
        sinonimos: ["mcp","claude code"],
        cuerpo: "",
        texto: "",
      },
    ],
  },
  {
    slug: "atajos-de-teclado",
    titulo: "Atajos de teclado",
    paginas: [
      {
        id: "atajos-de-teclado/atajos-de-teclado",
        titulo: "Atajos de teclado",
        tema: "Atajos de teclado",
        solo: null,
        pendiente: true,
        cubre: [],
        sinonimos: ["teclas","shortcuts","combinaciones"],
        cuerpo: "",
        texto: "",
      },
    ],
  },
];
